[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { version = "0.3.0" }


[features]
# Enables parallel processing support by enabling the "rayon" feature of jpeg-decoder.
cuda = ["candle-core/cuda"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
