[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[target.'cfg(not(target_os = "macos"))'.dependencies]
candle-core = { version = "0.3.0", features = ["cuda"] }

[target.'cfg(target_os = "macos")'.dependencies]
candle-core = { version = "0.3.0" }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
