name: Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain Setup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: [cargo, clippy, rustfmt]

      - name: Toolchain Info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Formatting
        run: |
          cd backend
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test
        run: |
          cd backend
          cargo test --all --all-features --verbose      

      - name: Build
        run: |
          cd backend
          cargo build --release --verbose