name: Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Lint
        run: |
          cd backend
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test
        run: |
          cd backend
          cargo check
          cargo test --all --verbose          

      - name: Build
        run: |
          cd backend
          cargo build --release --verbose
